version: '3'
services:
  n8n:
    build:
      context: .
      dockerfile: ./Dockerfile  # Your Dockerfile path
      args:
        - N8N_VERSION=0.186.0
    image: n8n-puppeteer
    container_name: n8n
    ports:
      - "5678:5678"
    cap_add:
      - SYS_ADMIN
