version: '3'
services:
  n8n:
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - N8N_VERSION=${N8N_VERSION}
    image: n8n-puppeteer
    container_name: npn
    ports:
      - "5688:5678"
    cap_add:
      - SYS_ADMIN
    volumes:
      - n8n_data:/home/node/.n8n  # Reference the named volume here
    privileged: true
    shm_size: 1gb
    networks:
      - cloudflare_default

volumes:
  n8n_data:  # Define the named volume here

networks:
  cloudflare_default:
    external: true
