name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: List Tags
      uses: actions/github-script@v5
      with:
        script: |
          const { data } = await github.git.listMatchingRefs({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/',
          });
          const tags = data.map(ref => ref.ref.replace('refs/tags/', ''));
          console.log(JSON.stringify(tags));
    - name: Select Tag UI
      if: always()
      uses: appleboy/label-commenter@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.issue.number }}
        labels: 'manual-deploy'
        message: 'Please select a tag to deploy:'
        dropdowns: |
          - name: 'Tag'
            options: ${{ steps.list_tags.outputs.result }}