name: List Tags

on:
  workflow_dispatch:

jobs:
  list_tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.list_tags.outputs.tags }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: List Tags
      id: list_tags
      run: |
        git fetch --tags
        echo "${{ toJson(git tag -l) }}" | jq -R . | jq -s .