name: Manual Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag:'
        required: true

jobs:
  check_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check if tag exists
      run: |
        if git rev-parse --verify --quiet ${{ github.event.inputs.releaseTag }}; then
          echo "Tag ${{ github.event.inputs.releaseTag }} exists"
        else
          echo "Tag ${{ github.event.inputs.releaseTag }} does not exist"
          exit 1
        fi

    - name: Validate tag format
      run: |
        if [[ ! "${{ github.event.inputs.releaseTag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
           echo "Provided tag does not match the desired format or contains .beta/.hotfix."
           exit 1
        fi

    - name: Check if tag is associated with a pre-release on GitHub
      uses: actions/github-script@v6
      with:
        script: |
          const tag = context.payload.inputs.releaseTag;
          const { owner, repo } = context.repo;
          const release = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
          if (release.data.prerelease) {
            console.error(`The provided tag ${tag} is associated with a pre-release on GitHub.`);
            process.exit(1);
          }

    - name: Check tag position among production releases
      run: |
        # Get all tags sorted by date (latest first) and filter out pre-release tags
        all_tags=($(git tag --sort=-creatordate | grep -v "\.beta" | grep -v "\.hotfix"))
        
        # Get the position of the provided tag
        tag_position=-1
        for i in "${!all_tags[@]}"; do
           if [[ "${all_tags[$i]}" == "${{ github.event.inputs.releaseTag }}" ]]; then
               tag_position=$i
               break
           fi
        done
        
        # Check the tag position
        if [[ $tag_position -gt 4 || $tag_position -lt 0 ]]; then
           echo "Provided tag is more than 5 tags before the latest or doesn't exist."
           exit 1
        fi

  determine_release:
    needs: check_tag
    runs-on: ubuntu-latest

    outputs:
      release: ${{ steps.check_pre_release.outputs.release_type }}

    steps:
    - name: Check if tag is pre-release
      id: check_pre_release
      if: needs.check_tag.result == 'success'
      run: |
        if [[ "${{ github.event.inputs.releaseTag }}" == *".beta" ]]; then
          echo "release_type=pre-release" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.inputs.releaseTag }}" == *".hotfix" ]]; then
          echo "release_type=hotfix" >> $GITHUB_OUTPUT
        else
          echo "release_type=production" >> $GITHUB_OUTPUT
        fi

  hello_pre_release:
    needs: determine_release
    if: needs.determine_release.outputs.release == 'pre-release'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Pre-Release World with Tag
      run: |
        echo "Hello Pre-Release World! You provided tag: ${{ github.event.inputs.releaseTag }}"

  hello_production:
    needs: determine_release
    if: needs.determine_release.outputs.release == 'production'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Production World with Tag
      run: |
        echo "Hello Production World! You provided tag: ${{ github.event.inputs.releaseTag }}"

  hello_hotfix:
    needs: determine_release
    if: needs.determine_release.outputs.release == 'hotfix'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Hotfix World with Tag
      run: |
        echo "Hello Hotfix World! You provided tag: ${{ github.event.inputs.releaseTag }}"
