name: Manual Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag:'
        required: true

jobs:
  check_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if tag exists
      run: |
        if git rev-parse --verify --quiet ${{ github.event.inputs.releaseTag }}; then
          echo "Tag ${{ github.event.inputs.releaseTag }} exists"
        else
          echo "Tag ${{ github.event.inputs.releaseTag }} does not exist"
          exit 1
        fi

    - name: Determine release type and print message
      run: |
        if [[ "${{ github.event.inputs.releaseTag }}" == *.beta ]]; then
          echo "Hello Pre-release World! You provided tag: ${{ github.event.inputs.releaseTag }}"
        else
          echo "Hello Production World! You provided tag: ${{ github.event.inputs.releaseTag }}"
        fi
