name: Manual Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag:'
        required: true
        options: ${{ secrets.tags }}

jobs:
  check_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if tag exists
      run: |
        if git rev-parse --verify --quiet ${{ github.event.inputs.releaseTag }}; then
          echo "Tag ${{ github.event.inputs.releaseTag }} exists"
        else
          echo "Tag ${{ github.event.inputs.releaseTag }} does not exist"
          exit 1
        fi

  determine_release:
    needs: check_tag
    runs-on: ubuntu-latest

    outputs:
      release: ${{ steps.check_pre_release.outputs.release_type }}

    steps:
    - name: Check if tag is pre-release
      id: check_pre_release
      if: needs.check_tag.result == 'success'
      run: |
        if [[ "${{ github.event.inputs.releaseTag }}" == *".beta" ]]; then
          echo "release_type=pre-release" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.inputs.releaseTag }}" == *".hotfix" ]]; then
          echo "release_type=hotfix" >> $GITHUB_OUTPUT
        else
          echo "release_type=production" >> $GITHUB_OUTPUT
        fi

  hello_pre_release:
    needs: determine_release
    if: needs.determine_release.outputs.release == 'pre-release'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Pre-Release World with Tag
      run: |
        echo "Hello Pre-Release World! You provided tag: ${{ github.event.inputs.releaseTag }}"

  hello_production:
    needs: determine_release
    if: needs.determine_release.outputs.release == 'false'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Production World with Tag
      run: |
        echo "Hello Production World! You provided tag: ${{ github.event.inputs.releaseTag }}"

  hello_hotfix:
    needs: determine_release
    if: needs.determine_release.outputs.release == 'hotfix'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Hotfix World with Tag
      run: |
        echo "Hello Hotfix World! You provided tag: ${{ github.event.inputs.releaseTag }}"