name: Manual Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag:'
        required: true

jobs:
  check_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if tag exists
      run: |
        if git rev-parse --verify --quiet ${{ github.event.inputs.releaseTag }}; then
          echo "Tag ${{ github.event.inputs.releaseTag }} exists"
        else
          echo "Tag ${{ github.event.inputs.releaseTag }} does not exist"
          exit 1
        fi

  determine_release:
    needs: check_tag
    runs-on: ubuntu-latest

    outputs:
      is_pre_release: ${{ steps.check_pre_release.outputs.is_pre_release }}

    steps:
    - name: Check if tag is pre-release
      id: check_pre_release
      if: needs.check_tag.result == 'success'
      run: |
        if [[ "${{ github.event.inputs.releaseTag }}" == *".beta" ]]; then
          echo "is_pre_release=true" >> $GITHUB_OUTPUT
        else
          echo "is_pre_release=false" >> $GITHUB_OUTPUT
        fi

  hello_pre_release:
    needs: determine_release
    if: needs.determine_release.outputs.is_pre_release == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Pre-Release World with Tag
      run: |
        echo "Hello Pre-Release World! You provided tag: ${{ github.event.inputs.releaseTag }}"

  hello_production:
    needs: determine_release
    if: needs.determine_release.outputs.is_pre_release == 'false'
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Production World with Tag
      run: |
        echo "Hello Production World! You provided tag: ${{ github.event.inputs.releaseTag }}"